version: '3.8'
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8095:8080"
    restart: unless-stopped
    healthcheck:
      test: [ "CMD", "curl", "--fail", "http://localhost:8080/health", "||", "exit", "1" ]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 5s